---
kind: pipeline
type: kubernetes
name: jparest

platform:
  os: linux
  arch: amd64

trigger:
  event:
    include:
    - push
    - pull_request

steps:
- name: test
  image: maven:3.8-openjdk-17
  commands:
  - mvn clean install

- name: set branch name
  image: maven:3.8-openjdk-17
  commands:
    - "branchName=$${DRONE_BRANCH}"
  when:
    branch:
      exclude: main

- name: sonar
  image: maven:3.8-openjdk-17
  depends_on:
  - test
  environment:
    SONAR_HOST:
      from_secret: sonar_cloud_host
    SONAR_TOKEN:
      from_secret: sonar_cloud_token
  commands:
  - mvn sonar:sonar -Dsonar.host.url=$${SONAR_HOST} -Dsonar.login=$${SONAR_TOKEN} -Dsonar.organization=ukhomeoffice -Dsonar.projectKey=callisto-jparest -Dsonar.branch.name=$${branchName}}
  when:
    event:
      exclude:
      - pull_request

- name: publish
  image: maven:3.8-openjdk-17
  depends_on:
    - sonar
  environment:
    ARTIFACTORY_TOKEN:
        from_secret: artifactory_token
  commands:
  - mvn -s ./jparest_settings.xml -f pom.xml install -B org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy -DskipTests
  - versionExtract=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
  - sed -i "/^version=/{s|.$|"=$versionExtract"|}" git_tag.sh
  when:
    branch: main
    event:
      exclude:
      - pull_request

- name: git tag
  image: alpine/git
  depends_on:
    - publish
  environment:
    SSH_KEY:
      from_secret: github_token
  commands:
    - chmod 777 git_tag.sh
    - ./git_tag.sh
  when:
    branch: main
    event:
      exclude:
      - pull_request

- name: snapshot
  image: maven:3.8-openjdk-17
  depends_on:
    - sonar
  environment:
    ARTIFACTORY_TOKEN:
      from_secret: artifactory_token
  commands:
    - "BRANCH=$(echo $DRONE_BRANCH | tr '[:lower:]' '[:upper:]') && [[ $BRANCH =~ (EAHW-[0-9]*) ]] && snapshotSuffix=$${match/#E/-E}$${BASH_REMATCH/#E/-E}"
    - version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - mvn versions:set -DnewVersion=$version$${snapshotSuffix}-SNAPSHOT -f pom.xml
    - mvn -s ./jparest_settings.xml -f pom.xml install -B org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy -DsnapshotSuffix=$${snapshotSuffix}-SNAPSHOT -DskipTests
  when:
    branch:
      exclude:
      - main

# - name: sonar pr decoration
#   image: maven:3.8-openjdk-17
#   depends_on:
#   - sonar
#   environment:
#     SONAR_HOST:
#       from_secret: sonar_host
#     SONAR_TOKEN:
#       from_secret: sonar_token
#   commands:
#   - echo this is where I run the pull request decoration
#   when:
#     event:
#       include:
#       - pull_request

---
kind: pipeline
type: kubernetes
name: sonar housekeeping

trigger:
  event:
  - cron
  cron:
    include:
    - nightly

steps:
- name: SonarQube housekeeping
  image: quay.io/ukhomeofficedigital/cicd-actions-sonarqube-housekeeping:v1
  settings:
    sonarqube_host: https://sonarqube.digital.homeoffice.gov.uk/
    sonarqube_token:
      from_secret: sonar_token
    sonarqube_project_prefix: 'callisto-jparest'
    jira_project_key: 'eahw'

---
kind: pipeline
type: kubernetes
name: build notifications

trigger:
  status:
    - success
    - failure
  event:
    - push

depends_on:
  - jparest

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: callisto-tech-notifications
      username: Drone
      template: |
        {{#success build.status}}
          Build #{{ build.number }} succeeded! :tada:
        {{else}}
          Build #{{ build.number }} failed :alert:
        {{/success}}
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
