name: auto_tag
on:
  push:
#    branches:
#      - main

jobs:
  build:
    name: Tag the Current Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version Variable
        id: project
        run: |
          mvn clean install -DSkipTests
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=version::$VERSION"
          echo ${{ steps.project.version }}