name: auto_tag
on:
  push:
#    branches:
#      - main

jobs:
  build:
    name: Tag the Current Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version Variable
        id: project
        run: |
          echo ::set-env name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "The version is: ${{ steps.project.outputs.version }}"
      - uses: actions/checkout@v2
      - name: Tag and Push Current Repo Code
        run: |
          git tag ${{ steps.project.outputs.version }}
          git push origin ${{ steps.project.outputs.version }}