name: auto_tag
on:
  push:
#    branches:
#      - main

jobs:
  build:
    name: Tag the Current Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version Variable
        id: project
        run: |
          "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo ${{ env.VERSION }}
      - uses: actions/checkout@v2
      - name: Tag and Push Current Repo Code
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}