name: auto_tag
on:
  push:
#    branches:
#      - main
jobs:
  tag_repo:
    name: Tag the Current Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag and Push Current Repo Code
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          git tag "$VERSION"
          git push origin "$VERSION"
