name: Publish
on:
  push:

jobs:
  deploy_to_artifactory:
    name: Deploy to Artifactory
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Publish to Artifactory
        uses: actions/setup-java@v1
        with:
          distribution: temurin
          java-version: '17'
          server-id: callisto-jparest
          server-username: ARTIFACTORY_USER
          server-password: ARTIFACTORY_TOKEN
      - name: Build with Maven
        run: |
        mvn -B package
        mvn -s ./settings.xml -f pom.xml install -B org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy -DsnapshotSuffix=$${snapshotSuffix}-SNAPSHOT -DskipTests

        id: publish
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
        


