name: auto_tag
on:
  push:
#    branches:
#      - main
jobs:
  tag_repo:
    name: Tag the Current Code
    runs-on: ubuntu-latest
    env:
      Version: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    steps:
      - uses: actions/checkout@v2
      - name: Tag and Push Current Repo Code
        run: |
          git tag "$Version"
          git push origin "$Version"
