name: auto_tag
on:
  push:
#    branches:
#      - main
jobs:
  tag_repo:
    name: Get runner id and tag the current code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tag and push current repo code
        run: |
          git tag 0.0.0
          git push origin 0.0.0
