name: Publish
on:
  push:

jobs:
  deploy_to_artifactory:
    name: Deploy to Artifactory
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: maven-settings-action
        uses: s4u/maven-settings-actions@v2.6.0
        with: 
          servers: |
            [{
              "id": "callisto-jparest",
              "configuration": {
                "httpHeaders": {
                  "property": {
                    "name": Authorization,
                    "value": "Bearer ${{ secrets.ARTIFACTORY_USER }}"
                  }
                }
              }
            }]

      - name: Build with Maven
        run: |
          mvn -B package
          mvn -s /home/runner/.m2/settings.xml -f pom.xml install -B org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy -DskipTests      
        id: publish
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
        


