name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish snapshot
        shell: bash
      run: |
          snapshotSuffix=${GITHUB_REF_NAME}
         "BRANCH=$(echo $DRONE_BRANCH | tr '[:lower:]' '[:upper:]') && [[ $BRANCH =~ (EAHW-[0-9]*) ]] && snapshotSuffix=$${match/#E/-E}$${BASH_REMATCH/#E/-E}"
      env: 
        GTIHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
# on:
#   branches:
#     - '!main'

# jobs:
#    name: Deploy Snapshot
#    runs-on: ubuntu-latest
#    steps:

#         - uses: actions/checkout@v2

#         - name: Set ud JDK 17
#            uses: actions/setup-java@v3
#            with:
#             java-version: 17

#         - name: build with Maven
#            run: mvn clean install

#         - name: Publish to Artifactory
#            run: |
#             "BRANCH=$(echo $DRONE_BRANCH | tr '[:lower:]' '[:upper:]') && [[ $BRANCH =~ (EAHW-[0-9]*) ]] && snapshotSuffix=$${match/#E/-E}$${BASH_REMATCH/#E/-E}"
#             mvn -s ./jparest_settings.xml -f pom.xml install -B org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy -DsnapshotSuffix=$${snapshotSuffix}-SNAPSHOT -DskipTests

# name: auto_tag
# on:
#   push:
# #    branches:
# #      - main

# jobs:
#   build:
#     name: Tag the Current Code
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set Version Variable
#         id: project
#         run: |
#           mvn clean install -DSkipTests
#           VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
#           echo "::set-output name=version::$VERSION"
#           echo ${{ steps.project.version }}

# name: Snapshot
# on:
#   branches:
#     - '!main'

# jobs:
#    name: Deploy Snapshot
#    runs-on: ubuntu-latest
#    steps:

#         - uses: actions/checkout@v2

#         - name: Set ud JDK 17
#            uses: actions/setup-java@v3
#            with:
#             java-version: 17

#         - name: build with Maven
#            run: mvn clean install

#         - name: Publish to Artifactory
#            run: |
#             "BRANCH=$(echo $DRONE_BRANCH | tr '[:lower:]' '[:upper:]') && [[ $BRANCH =~ (EAHW-[0-9]*) ]] && snapshotSuffix=$${match/#E/-E}$${BASH_REMATCH/#E/-E}"
#             mvn -s ./jparest_settings.xml -f pom.xml install -B org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy -DsnapshotSuffix=$${snapshotSuffix}-SNAPSHOT -DskipTests