name: Publish
on:
  push:
    branches:
      - dev/eahw-2109/publish-jparest-github-actions

jobs:
  deploy_to_artifactory:
    name: Deploy to Artifactory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven
        id: Maven
        run: mvn --batch-mode package

      - name: Publish to Artifactory
        id: publish
        run: mvn -s ./jparest_settings.xml -f pom.xml install -B org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy -DskipTests
        env:
          registry: https://artifactory.digital.homeoffice.gov.uk/artifactory/callisto-jparest
          ARTIFACTORY_TOKEN: "${{ secrets.ARTIFACTORY_TOKEN }}"


